name: etcFBA
channels:
  - gurobi
  - https://conda.anaconda.org/gurobi
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.3.2=py38h578d9bd_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.1=openblas
  - bleach=4.1.0=pyhd8ed1ab_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.6=py38h3931269_1
  - charset-normalizer=2.0.6=pyhd8ed1ab_0
  - cobra=0.21.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - commonmark=0.9.1=py_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - depinfo=1.7.0=pyhd8ed1ab_0
  - diskcache=5.2.1=pyh44b312d_0
  - entrypoints=0.3=py38h32f6830_1002
  - expat=2.4.1=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py38h578d9bd_3
  - gettext=0.19.8.1=h73d1719_1008
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.0b5=py38h8384b0a_0
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - gurobi=9.1.2=py38_0
  - h11=0.12.0=pyhd8ed1ab_0
  - h2=4.1.0=py38h578d9bd_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.13.7=pyhd8ed1ab_0
  - httpx=0.19.0=py38h578d9bd_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - importlib_metadata=4.8.1=hd8ed1ab_0
  - importlib_resources=5.2.2=pyhd8ed1ab_0
  - ipykernel=6.4.1=py38he5a9106_0
  - ipython=7.28.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.0.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h578d9bd_6
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_1
  - jupyter_core=4.8.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.19.2=hcc1bbae_2
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libclang=11.1.0=default_ha53f305_1
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc-ng=11.2.0=h1d223b6_9
  - libgfortran=3.0.0=1
  - libgfortran-ng=11.2.0=h69a702a_9
  - libgfortran5=11.2.0=h5c6108e_9
  - libglib=2.68.4=h174f98d_1
  - libgomp=11.2.0=h1d223b6_9
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm10=10.0.1=he513fc3_3
  - libllvm11=11.1.0=hf817b99_2
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_9
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1004
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.2.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.4=pyha770c72_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_1
  - numpy=1.21.2=py38he2449b9_0
  - olefile=0.46=pyh9f0ad1d_1
  - openblas=0.2.20=8
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - optlang=1.4.4=pyh9f0ad1d_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py38h43a58ef_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1002
  - pillow=8.3.2=py38h8e6f84c_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pprintpp=0.4.0=py38h578d9bd_2
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.8.2=py38h497a2fe_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - python=3.8.12=hb7a2778_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-libsbml=5.19.0=py38h709712a_1
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=22.3.0=py38h2035c66_0
  - qt=5.12.9=hda022c4_4
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.11.2=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - rfc3986=1.5.0=pyhd8ed1ab_0
  - rich=6.2.0=py38h32f6830_0
  - ruamel.yaml=0.17.16=py38h497a2fe_0
  - ruamel.yaml.clib=0.2.2=py38h497a2fe_2
  - scikit-learn=1.0=py38hacb3eff_1
  - scipy=1.7.1=py38h56a6a73_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.2.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py38h578d9bd_1
  - sqlite=3.36.0=h9cd32fc_2
  - statsmodels=0.13.0=py38h6c62de6_0
  - swiglpk=5.0.3=py38h15e1503_0
  - sympy=1.8=py38h578d9bd_0
  - terminado=0.12.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
prefix: /home/jakobpp/miniconda3/envs/etcFBA
